Repository opensearch-project/security-analytics, pull requests merged in 2023-09, with the labels that each got.

#529 segment replication changes
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
  src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
  src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchCorrelationRuleAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportListCorrelationAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportSearchCorrelationAction.java
  src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java
  src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
  src/main/java/org/opensearch/securityanalytics/util/RuleValidator.java
Labels: backport 2.x

#535 Use core OpenSearch version of commons-lang3
  build.gradle
Labels: backport 2.x

#536 Force google guava to 32.0.1
  build.gradle
Labels: backport 2.x

#532 add mitre attack based auto-correlations support in correlation engine
  src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
  src/main/java/org/opensearch/securityanalytics/util/AutoCorrelationsRepo.java
  src/main/resources/correlations/mitre_correlation.json
  src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
Labels: backport 2.x

#543 Updates demo certs used in integ tests
  src/test/resources/sample.pem
  src/test/resources/test-kirk.jks
Labels: backport 2.x, v2.10.0

#539 Auto expand replicas
  src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
Labels: backport 2.x, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#555 Added 2.10.0 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.10.0.0.md
Labels: backport 2.x, backport 2.10

#545 adds support for alerts and triggers on group by based sigma rules
  src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java
  src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x, backport 2.10

#559 Backport 2.x adds support for alerts and triggers on group by based sigma rules (#545)
  src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java
  src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.10

#568 auto expand replicas for logtype index
  src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java
  src/main/java/org/opensearch/securityanalytics/util/CustomLogTypeIndices.java
Labels: backport 2.x, backport 2.9, backport 2.10

#438 Match maintainer account username.
  MAINTAINERS.md
Labels: backport 2.x

#596 ignore tests that may be flaky
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Labels: backport 2.x, backport 2.10
