Repository opensearch-project/security-analytics, pull requests merged in 2023-02, with the labels that each got.

#321 log message change for debugging
  src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
Labels: backport 2.x, backport 2.5

#329 Baselined MAINTAINERS and CODEOWNERS docs.
  CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#278 update others_apt mappings
  src/main/resources/OSMapping/others_apt/fieldmappings.yml
  src/main/resources/OSMapping/others_apt/mappings.json
Labels: backport 2.x, backport 2.5

#335 query_field_names bugfix
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
  src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
  src/main/resources/mappings/rules.json
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
Labels: backport 2.x

#327 GetAllRuleCategories API
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/action/GetAllRuleCategoriesAction.java
  src/main/java/org/opensearch/securityanalytics/action/GetAllRuleCategoriesRequest.java
  src/main/java/org/opensearch/securityanalytics/action/GetAllRuleCategoriesResponse.java
  src/main/java/org/opensearch/securityanalytics/model/RuleCategory.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAllRuleCategoriesAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetAllRuleCategoriesAction.java
  src/main/resources/rules/rule_categories.json
  src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Labels: backport 2.x

#301 update others_cloud mappings
  src/main/resources/OSMapping/others_cloud/fieldmappings.yml
  src/main/resources/OSMapping/others_cloud/mappings.json
Labels: backport 2.x, backport 2.5

#302 update others_compliance mappings
  src/main/resources/OSMapping/others_compliance/fieldmappings.yml
  src/main/resources/OSMapping/others_compliance/mappings.json
Labels: backport 2.x, backport 2.5

#304 update others_web mappings
  src/main/resources/OSMapping/others_web/fieldmappings.yml
  src/main/resources/OSMapping/others_web/mappings.json
Labels: backport 2.x, backport 2.5

#352 Publish snapshots to maven via GHA
  .github/workflows/maven-publish.yml
  build.gradle
Labels: backport 2.x

#336 Support for multiple indices in detector input
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x, backport 2.6

#363 fix for integ test failures in 2.6
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
Labels: backport 2.6
