Repository opensearch-project/security-analytics, pull requests merged in 2023-01, with the labels that each got.

#211 updated network mappings
  src/main/resources/OSMapping/network/fieldmappings.yml
  src/main/resources/OSMapping/network/mappings.json
Labels: backport 2.x

#197 Added dummy search when creating detector on the given indicies
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SecureDetectorRestApiIT.java
Labels: backport 2.x

#248 [Pen test]Service Returns Unhandled Error Response
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Labels: backport 2.x

#212 updated windows mappings
  src/main/resources/OSMapping/windows/fieldmappings.yml
  src/main/resources/OSMapping/windows/mappings.json
Labels: backport 2.x

#253 fix ci builds for security-analytics
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x

#215 Removed create/delete queryIndex
  build.gradle
  src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/main/java/org/opensearch/securityanalytics/mapper/MapperUtils.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportCreateIndexMappingsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
  src/main/resources/mappings/detector-queries.json
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperServiceTests.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperUtilsTests.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x

#245 GetMappingsView API - index pattern/alias/datastream support
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetMappingsViewAction.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperUtilsTests.java
Labels: backport 2.x

#240 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: backport 2.x, backport 2.5

#268 Added 2.5 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#264 add mapping fixes
  src/main/resources/OSMapping/cloudtrail/fieldmappings.yml
  src/main/resources/OSMapping/linux/mappings.json
  src/main/resources/rules/ad_ldap/azure_aad_secops_signin_failure_bad_password_threshold.yml
  src/main/resources/rules/ad_ldap/azure_aadhybridhealth_adfs_new_server.yml
  src/main/resources/rules/ad_ldap/azure_aadhybridhealth_adfs_service_delete.yml
  src/main/resources/rules/ad_ldap/azure_ad_bitlocker_key_retrieval.yml
  src/main/resources/rules/ad_ldap/azure_ad_device_registration_or_join_without_mfa.yml
  src/main/resources/rules/ad_ldap/azure_ad_device_registration_policy_changes.yml
  src/main/resources/rules/ad_ldap/azure_ad_sign_ins_from_noncompliant_devices.yml
  src/main/resources/rules/ad_ldap/azure_ad_sign_ins_from_unknown_devices.yml
  src/main/resources/rules/ad_ldap/azure_ad_user_added_to_admin_role.yml
  src/main/resources/rules/ad_ldap/azure_ad_users_added_to_device_admin_roles.yml
  src/main/resources/rules/ad_ldap/win_ldap_recon.yml
  src/main/resources/rules/cloudtrail/aws_s3_data_management_tampering.yml
  src/main/resources/rules/windows/builtin/system/win_sample_rule.yml
Labels: backport 2.x, backport 2.5

#263 correct linux mapping error
  src/main/resources/OSMapping/linux/mappings.json
Labels: backport 2.x, backport 2.5

#262 Adds timestamp field alias and sets time range filter in bucket level monitor
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/main/resources/OSMapping/ad_ldap/fieldmappings.yml
  src/main/resources/OSMapping/ad_ldap/mappings.json
  src/main/resources/OSMapping/apache_access/fieldmappings.yml
  src/main/resources/OSMapping/apache_access/mappings.json
  src/main/resources/OSMapping/cloudtrail/fieldmappings.yml
  src/main/resources/OSMapping/cloudtrail/mappings.json
  src/main/resources/OSMapping/dns/fieldmappings.yml
  src/main/resources/OSMapping/dns/mappings.json
  src/main/resources/OSMapping/linux/fieldmappings.yml
  src/main/resources/OSMapping/linux/mappings.json
  src/main/resources/OSMapping/network/NetFlowMapping.json
  src/main/resources/OSMapping/network/fieldmappings.yml
  src/main/resources/OSMapping/network/mappings.json
  src/main/resources/OSMapping/others_application/fieldmappings.yml
  src/main/resources/OSMapping/others_application/mappings.json
  src/main/resources/OSMapping/others_apt/fieldmappings.yml
  src/main/resources/OSMapping/others_apt/mappings.json
  src/main/resources/OSMapping/others_cloud/fieldmappings.yml
  src/main/resources/OSMapping/others_cloud/mappings.json
  src/main/resources/OSMapping/others_compliance/fieldmappings.yml
  src/main/resources/OSMapping/others_compliance/mappings.json
  src/main/resources/OSMapping/others_macos/fieldmappings.yml
  src/main/resources/OSMapping/others_macos/mappings.json
  src/main/resources/OSMapping/others_proxy/fieldmappings.yml
  src/main/resources/OSMapping/others_proxy/mappings.json
  src/main/resources/OSMapping/others_web/fieldmappings.yml
  src/main/resources/OSMapping/others_web/mappings.json
  src/main/resources/OSMapping/s3/fieldmappings.yml
  src/main/resources/OSMapping/s3/mappings.json
  src/main/resources/OSMapping/test_windows/fieldmappings.yml
  src/main/resources/OSMapping/test_windows/mappings.json
  src/main/resources/OSMapping/windows/fieldmappings.yml
  src/main/resources/OSMapping/windows/mappings.json
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x, backport 2.5

#280 [Backport 2.x] Service Returns Unhandled Error Response (#248)
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Labels: backport 2.5

#279 [Backport 2.x] Adds timestamp field alias and sets time range filter …
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/main/resources/OSMapping/ad_ldap/fieldmappings.yml
  src/main/resources/OSMapping/ad_ldap/mappings.json
  src/main/resources/OSMapping/apache_access/fieldmappings.yml
  src/main/resources/OSMapping/apache_access/mappings.json
  src/main/resources/OSMapping/cloudtrail/fieldmappings.yml
  src/main/resources/OSMapping/cloudtrail/mappings.json
  src/main/resources/OSMapping/dns/fieldmappings.yml
  src/main/resources/OSMapping/dns/mappings.json
  src/main/resources/OSMapping/linux/fieldmappings.yml
  src/main/resources/OSMapping/linux/mappings.json
  src/main/resources/OSMapping/network/NetFlowMapping.json
  src/main/resources/OSMapping/network/fieldmappings.yml
  src/main/resources/OSMapping/network/mappings.json
  src/main/resources/OSMapping/others_application/fieldmappings.yml
  src/main/resources/OSMapping/others_application/mappings.json
  src/main/resources/OSMapping/others_apt/fieldmappings.yml
  src/main/resources/OSMapping/others_apt/mappings.json
  src/main/resources/OSMapping/others_cloud/fieldmappings.yml
  src/main/resources/OSMapping/others_cloud/mappings.json
  src/main/resources/OSMapping/others_compliance/fieldmappings.yml
  src/main/resources/OSMapping/others_compliance/mappings.json
  src/main/resources/OSMapping/others_macos/fieldmappings.yml
  src/main/resources/OSMapping/others_macos/mappings.json
  src/main/resources/OSMapping/others_proxy/fieldmappings.yml
  src/main/resources/OSMapping/others_proxy/mappings.json
  src/main/resources/OSMapping/others_web/fieldmappings.yml
  src/main/resources/OSMapping/others_web/mappings.json
  src/main/resources/OSMapping/s3/fieldmappings.yml
  src/main/resources/OSMapping/s3/mappings.json
  src/main/resources/OSMapping/test_windows/fieldmappings.yml
  src/main/resources/OSMapping/test_windows/mappings.json
  src/main/resources/OSMapping/windows/fieldmappings.yml
  src/main/resources/OSMapping/windows/mappings.json
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.5

#283 index template conflict resovle; GetIndexMappings API changes
  src/main/java/org/opensearch/securityanalytics/mapper/IndexTemplateManager.java
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
Labels: backport 2.x, backport 2.5

#286 add nesting level to yaml constructor
  src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaRule.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.x, backport 2.5

#293 GetIndexMapping API bugfix
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MappingsTraverserTests.java
Labels: backport 2.x, backport 2.5
