Repository opensearch-project/security-analytics, pull requests merged in 2023-07, with the labels that each got.

#479 [backport 2.x] Gradle update
  build-tools/opensearchplugin-coverage.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/org/opensearch/securityanalytics/action/CreateIndexMappingsRequest.java
  src/main/java/org/opensearch/securityanalytics/action/GetIndexMappingsResponse.java
  src/main/java/org/opensearch/securityanalytics/action/GetMappingsViewResponse.java
  src/main/java/org/opensearch/securityanalytics/action/ValidateRulesRequest.java
  src/main/java/org/opensearch/securityanalytics/action/ValidateRulesResponse.java
  src/main/java/org/opensearch/securityanalytics/correlation/index/query/CorrelationQueryBuilder.java
  src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
  src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/correlation/LuceneEngineIT.java
  src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Labels: backport 2.9

#486 Added 2.9 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#500 Custom log type implementation
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/action/CorrelatedFindingRequest.java
  src/main/java/org/opensearch/securityanalytics/action/DeleteCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/action/DeleteCustomLogTypeRequest.java
  src/main/java/org/opensearch/securityanalytics/action/DeleteCustomLogTypeResponse.java
  src/main/java/org/opensearch/securityanalytics/action/IndexCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/action/IndexCustomLogTypeRequest.java
  src/main/java/org/opensearch/securityanalytics/action/IndexCustomLogTypeResponse.java
  src/main/java/org/opensearch/securityanalytics/action/SearchCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/action/SearchCustomLogTypeRequest.java
  src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
  src/main/java/org/opensearch/securityanalytics/logtype/BuiltinLogTypeLoader.java
  src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java
  src/main/java/org/opensearch/securityanalytics/model/CustomLogType.java
  src/main/java/org/opensearch/securityanalytics/model/Detector.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestDeleteCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchCorrelationAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetAllRuleCategoriesAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportSearchCorrelationAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportSearchCustomLogTypeAction.java
  src/main/java/org/opensearch/securityanalytics/util/CustomLogTypeIndices.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
  src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
  src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
  src/main/resources/OSMapping/ad_ldap/fieldmappings.yml
  src/main/resources/OSMapping/logtypes.json
  src/main/resources/mappings/log_type_config_mapping.json
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/action/IndexDetectorResponseTests.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
  src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
  src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Labels: backport main, backport 2.9
