Repository opensearch-project/security-analytics, pull requests merged in 2024-10, with the labels that each got.

#1358 update number of replicas of system indices to 1-20 and number of primary shards for system indices to 1
  src/main/java/org/opensearch/securityanalytics/indexmanagment/DetectorIndexManagementService.java
  src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dao/BaseEntityCrudService.java
  src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java
  src/main/java/org/opensearch/securityanalytics/util/CorrelationRuleIndices.java
  src/main/java/org/opensearch/securityanalytics/util/CustomLogTypeIndices.java
  src/main/java/org/opensearch/securityanalytics/util/DetectorIndices.java
  src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
Labels: backport 2.x, backport 2.17

#1364 update min number of replicas to 0
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
Labels: backport 2.x, backport 2.15, backport 2.17

#1371 update min number of replicas to 0
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
Labels: backport 2.15

#1372 fix for detectors with sigma aggregation rules
  src/main/java/org/opensearch/securityanalytics/mapper/IndexTemplateManager.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.17

#1373 [Bug] Fixed ListIOCs number of findings cap.
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16, backport 2.17

#1383 fix search monitor query in update threat intel alert status API
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
Labels: backport 2.x, backport 2.10, backport 2.15, backport 2.17

#1382 set the refresh policy to IMMEDIATE when updating correlation alerts
  src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationAlertService.java
Labels: backport 2.15, backport 2.16, backport 2.17, backport 2.18

#1392 [Bug] Add exists check for IOCs index.
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
Labels: backport 2.x, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#1399 Added 2.18 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0, backport 2.18

#1393 Add validation for threat intel source config
  src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
  src/test/java/org/opensearch/securityanalytics/action/IndexTIFSourceConfigRequestTests.java
  src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigDtoTests.java
  src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigTests.java
Labels: backport 2.x, backport 2.15, backport 2.16, backport 2.17, backport 2.18
