Repository opensearch-project/security-analytics, pull requests merged in 2024-05, with the labels that each got.

#1009 Added 2.14.0 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.14.0.0.md
Labels: backport 2.x, backport 2.14

#1019 fix chained findings monitor logic in update detector flow
  src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Labels: backport 2.11, backport 2.13

#1030 change default filter to time based fields
  src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java
Labels: backport 2.x, backport 2.11, backport 2.12, backport 2.13, backport 2.14

#1039 changes to add start_time and end_time filters to GetAlertsRequest
  src/main/java/org/opensearch/securityanalytics/action/GetAlertsRequest.java
  src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java
  src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportAcknowledgeAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Labels: backport 2.x, backport 2.11, backport 2.12, backport 2.13, backport 2.14
