Repository opensearch-project/security-analytics, pull requests merged in 2024-06, with the labels that each got.

#1047 fix upgrade issues due to lucene codec name change
  src/main/java/org/opensearch/securityanalytics/correlation/index/codec/CorrelationCodecVersion.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Labels: backport 2.x, backport 2.13, backport 2.14

#1055 Update 2.x to 2.15.0
  build.gradle
  src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java
Labels: release, v2.15.0

#1070 Updated the 2.15 release notes
  release-notes/opensearch-security-analytics.release-notes-2.15.0.0.md
Labels: backport 2.x, v2.15.0

#1082 pass integ tests
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
  src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
  src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
Labels: backport 2.x, backport 2.15
