Repository opensearch-project/security-analytics, pull requests merged in 2024-07, with the labels that each got.

#1163 ListIOCs API to return number of findings per IOC.
  src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15

#1162 Ioc upload integ tests and fix update
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
Labels: backport 2.x, backport 2.15

#1173 [BUG] Resolve aliases in monitor input to concrete indices before computing ioc-containing fields from concrete index docs
  src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/IocScanContext.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/TransportThreatIntelMonitorFanOutAction.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15

#1184 fix bug: threat intel monitor finding doesnt contain all doc_ids containing malicious IOC
  src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java
Labels: backport 2.x, backport 2.15

#1187 Fixed bulk indexing for IOCs.
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
Labels: backport 2.x, backport 2.15

#1197 Incremented version to 2.16.0.
  build.gradle
Labels: backport 2.16

#1207 Adds user validation for threat intel transport layer classes and stashes the thread context for all system index interactions
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportDeleteTIFSourceConfigAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetIocFindingsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetTIFSourceConfigAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportPutTIFJobAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportRefreshTIFSourceConfigAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportSearchTIFSourceConfigsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportDeleteThreatIntelMonitorAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportSearchThreatIntelMonitorAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
Labels: backport 2.x, backport 2.15, backport 2.16
