Repository opensearch-project/security-analytics, pull requests merged in 2024-09, with the labels that each got.

#1274 Fix threat intel multinode tests
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
Labels: backport 2.x, backport 2.16, backport 2.17

#1272 Update threat intel job mapping to new version
  src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobRunner.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportPutTIFJobAction.java
  src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
  src/main/resources/mappings/threat_intel_job_mapping.json
  src/test/java/org/opensearch/securityanalytics/TestHelpers.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/threatIntel/common/ThreatIntelLockServiceTests.java
Labels: backport 2.x, backport 2.15, backport 2.16, backport 2.17

#1278 Stash context for List IOCs Api
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsActionRequest.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsActionResponse.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestListIOCsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16, backport 2.17

#1292 Added 2.17.0 release notes
  release-notes/opensearch-security-analytics.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#1297 Stashcontext sa
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportAckCorrelationAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportGetCorrelationAlertsAction.java
Labels: backport 2.x, backport 2.17

#1305 upgrade upload artifacts
  .github/workflows/ci.yml
  .github/workflows/multi-node-test-workflow.yml
Labels: backport 2.x, backport 2.17

#1324 separate doc-level monitor query indices created by detectors
  src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
  src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
  src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
  src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
  src/test/java/org/opensearch/securityanalytics/DetectorThreatIntelIT.java
  src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
  src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
  src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/threatIntel/model/monitor/ThreatIntelInputTests.java
  src/test/resources/ad_ldap-sample.json
  src/test/resources/cloudtrail-sample.json
  src/test/resources/waf-sample.json
Labels: backport 2.x, backport 2.15, backport 2.16

#1331 add release notes for 2.17.1
  release-notes/opensearch-security-analytics.release-notes-2.17.1.0.md
Labels: backport 2.x, backport 2.17
