Repository opensearch-project/security-analytics, pull requests merged in 2024-08, with the labels that each got.

#1213 fix mappings integ tests
  src/test/resources/ad_ldap-sample.json
  src/test/resources/azure-sample.json
  src/test/resources/cloudtrail-sample.json
  src/test/resources/s3-sample.json
  src/test/resources/waf-sample.json
Labels: backport 2.x, backport 2.16

#1217 update build.gradle to use alerting-spi snapshot version
  build.gradle
Labels: backport 2.x, backport 2.16

#1226 added triggers in getDetectors API response
  src/main/java/org/opensearch/securityanalytics/action/GetDetectorResponse.java
Labels: backport 2.x, backport 2.15, backport 2.16

#1234 make threat intel run with standard detectors
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16

#1239 Fixed searchString bug. Removed nested IOC mapping structure.
  src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/SaIoCScanService.java
  src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
  src/main/resources/mappings/stix2_ioc_mapping.json
  src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16

#1240 adds toggling refresh disable/enable for deactivate/activate operation while updating URL_DOWNLOAD type configs
  src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAGetTIFSourceConfigResponse.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigResponse.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16

#1257 Fix S3 validation errors not caught by action listener
  src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16

#1263 Incremented version to 2.17.0.
  build.gradle
Labels: v2.17.0

#1267 Clean up empty IOC indices created by failed source configs
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
  src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
  src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
Labels: backport 2.x, backport 2.15, backport 2.16
