Repository opensearch-project/security-analytics, pull requests merged in 2025-02, with the labels that each got.

#1464 Refactored flaky test.
  src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Labels: backport 2.19

#1468 Added 2.19 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.19.0.0.md
Labels: backport 2.x, v2.19.0, backport 2.19

#1480 Incremented version to 2.19.1.
  build.gradle
Labels: v2.19.1

#1489 Added 2.19.1 release notes.
  release-notes/opensearch-security-analytics.release-notes-2.19.1.0.md
Labels: v2.19.1

#1492 Update gradle 8.10.2 and support jdk23
  .github/workflows/ci.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: release, v3.0.0
